declare module 'virtual:posts' {
    /**
     * Compiled posts keyed by slug, generated by
     * scripts/posts-manifest-plugin.ts. Unpublished posts are absent from
     * production builds and present during development.
     */
    export const postModules: Record<
        string,
        {
            default: import('react').ComponentType;
            frontmatter: Record<string, unknown>;
        }
    >;
}
